# Generated by Django 6.0.4 on 2026-05-05 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='service',
        ),
        migrations.RemoveField(
            model_name='hiringtransaction',
            name='service',
        ),
        migrations.AddField(
            model_name='booking',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.providerregistration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hiringtransaction',
            name='registration',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hiring_transactions', to='main.providerregistration'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
