# Generated by Django 6.0.4 on 2026-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_idempotencykey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
