# Generated by Django 6.0.4 on 2026-05-05 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_clientprofile_phone_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(max_length=50)),
                ('category_name', models.CharField(max_length=100)),
                ('foto_diri', models.TextField(blank=True, null=True)),
                ('provinsi_id', models.CharField(blank=True, max_length=20, null=True)),
                ('provinsi_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kota_id', models.CharField(blank=True, max_length=20, null=True)),
                ('kota_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kecamatan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('kecamatan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('kelurahan_id', models.CharField(blank=True, max_length=20, null=True)),
                ('kelurahan_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('pengalaman', models.TextField(blank=True, null=True)),
                ('tahun_pengalaman', models.IntegerField(default=0)),
                ('gaji_diharapkan', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'providers_registration',
                'ordering': ['-created_at'],
            },
        ),
    ]
